name: Tonkeeper Playwright
on:
    workflow_dispatch:
jobs:
    playwright-tests:
        name: playwright-tests
        runs-on: windows-latest
        timeout-minutes: 20

        steps:
            - name: Checkout to git repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20.11.1

            - name: Enable Corepack
              run: |
                  corepack enable

            - name: Run install
              uses: borales/actions-yarn@v5
              with:
                  dir: 'tests/playwright'
                  cmd: install

            - name: Run playwright install
              uses: borales/actions-yarn@v5
              with:
                  dir: 'tests/playwright'
                  cmd: playwright install

            - name: Run install
              uses: borales/actions-yarn@v5
              env:
                  BASE_APP_URL: https://wallet.tonkeeper.com
                  TON_MNEMONIC_24: ${{ secrets.TON_MNEMONIC_24 }}
                  TON_MNEMONIC_24_2: ${{ secrets.TON_MNEMONIC_24_2 }} 
                  TON_MNEMONIC_24_3: ${{ secrets.TON_MNEMONIC_24_3 }} 
                  TON_MNEMONIC_24_4: ${{ secrets.TON_MNEMONIC_24_4 }} 
                  TON_MNEMONIC_24_5: ${{ secrets.TON_MNEMONIC_24_5 }} 
                  TON_MNEMONIC_ANANAS: ${{ secrets.TON_MNEMONIC_ANANAS }} 
                  TON_MNEMONIC_12: ${{ secrets.TON_MNEMONIC_12 }} 
                  TON_MNEMONIC_12_2: ${{ secrets.TON_MNEMONIC_12_2 }} 
              with:
                  dir: 'tests/playwright'
                  cmd: test

          - uses: actions/upload-artifact@v4
            if: ${{ !cancelled() }}
            with:
              name: playwright-report
              path: tests/playwright/playwright-report/
              retention-days: 10